version: 2
updates:

  # Maintain dependencies for Poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Docker
    - package-ecosystem: "docker"
      directory: "/"
      schedule:
        interval: "daily"