version: '3.7'
services:
    compile: &BASE
        build: .
        volumes:
            - .:/package

    tests:
        <<: *BASE
        command: bash -c "poetry run black --check . --exclude lib && poetry run pytest -v tests"